export const sections = [
  {
    slug: "sahitya",
    label: "साहित्य",
    categories: [
      { slug: "kavita", label: "कविता" },
      { slug: "kahani", label: "कहानी" },
      { slug: "upanyas", label: "उपन्यास" },
      { slug: "laghu-upanyas", label: "लघु उपन्यास" },
      { slug: "alochana", label: "आलोचना" },
      { slug: "pustak-sameeksha", label: "पुस्तक समीक्षा" },
      { slug: "nibandh", label: "निबंध" },
      { slug: "paricharcha", label: "परिचर्चा" },
      { slug: "aatmakatha", label: "आत्मकथा" },
      { slug: "sansmaran", label: "संस्मरण" },
      { slug: "jeevani", label: "जीवनी" },
      { slug: "reportaz", label: "रिपोर्ताज" },
      { slug: "diary", label: "डायरी" },
      { slug: "laghukatha", label: "लघुकथा" },
      { slug: "natak", label: "नाटक" },
      { slug: "ekanki", label: "एकांकी" },
      { slug: "sakshatkar", label: "साक्षात्कार" },
      { slug: "yatra-vrittant", label: "यात्रा वृत्तांत" },
      { slug: "sahitya-samachar", label: "साहित्य समाचार" },
    ],
  },
  {
    slug: "samachar",
    label: "समाचार",
    categories: [
      { slug: "rashtriya", label: "राष्ट्रीय समाचार" },
      { slug: "vishwa", label: "विश्व समाचार" },
      { slug: "rajya", label: "राज्य समाचार" },
      { slug: "apradh-aatank", label: "अपराध और आतंक" },
      { slug: "sangathit-apradh", label: "संगठित अपराध" },
      { slug: "samarik-suraksha", label: "सामरिक सुरक्षा" },
      { slug: "aatankwad-suraksha-bal", label: "आतंकवाद और सुरक्षाबल" },
      { slug: "naxal-samasya", label: "नक्सल समस्या" },
      { slug: "purvottar-bharat", label: "पूर्वोत्तर भारत" },
      { slug: "bharat-pakistan", label: "भारत-पाकिस्तान" },
      { slug: "yuddh-shanti", label: "युद्ध और शांति" },
    ],
  },
  {
    slug: "rajniti-shasan",
    label: "राजनीति-शासन",
    categories: [
      { slug: "kendriya-sarkar", label: "केन्द्रीय सरकार" },
      { slug: "pradhanmantri-mantrimandal", label: "प्रधानमंत्री: मंत्रिमंडल" },
      { slug: "bihar-sarkar", label: "बिहार: सरकार और प्रशासन" },
      { slug: "sansad", label: "संसद का गलियारा" },
      { slug: "bihar-rajnitik-dal", label: "बिहार: राजनीतिक दल" },
      { slug: "sarkar-shasan", label: "सरकार और शासन" },
      { slug: "dakshin-bharat-rajniti", label: "दक्षिण भारत: राजनीति" },
      { slug: "loktantra-samaj", label: "लोकतंत्र और समाज" },
      { slug: "kanoon-vidhan", label: "कानून और विधान" },
      { slug: "manavadhikar", label: "मानवाधिकार" },
      { slug: "citizen-charter", label: "सिटिज़न चार्टर" },
      { slug: "antarrashtriya-sahyog", label: "अंतरराष्ट्रीय सहयोग और विकास" },
    ],
  },
  {
    slug: "samaj",
    label: "समाज",
    categories: [
      { slug: "nari-jeevan", label: "नारी जीवन" },
      { slug: "samaj-utthan", label: "समाज उत्थान" },
      { slug: "kasba", label: "समाज और परिवेश: कस्बा" },
      { slug: "mahanagar", label: "महानगर" },
      { slug: "abhijatya-jeevan", label: "अभिजात्य जीवन" },
      { slug: "dalit-jeevan", label: "दलित जीवन" },
      { slug: "aadivasi", label: "आदिवासी" },
      { slug: "bal-jeevan", label: "बाल जीवन" },
      { slug: "kishor-jeevan", label: "किशोर और किशोरियों का जीवन" },
      { slug: "vridh-jeevan", label: "वृद्ध और बुजुर्ग" },
      { slug: "shiksha-vyavastha", label: "शिक्षा व्यवस्था" },
      { slug: "media-jagat", label: "मीडिया जगत" },
      { slug: "gram-sansar", label: "ग्राम संसार" },
      { slug: "charitra-nirman", label: "चरित्र निर्माण" },
      { slug: "manav-kalyan", label: "मानव कल्याण" },
      { slug: "vikas-visthapan", label: "विकास और विस्थापन" },
      { slug: "gandhi-ashram", label: "गांधी आश्रम" },
      { slug: "anaitik-karobar", label: "अनैतिक कारोबार" },
      { slug: "madak-dravya-unmoolan", label: "मादक द्रव्य उन्मूलन" },
    ],
  },
  {
    slug: "sanskriti-dharm",
    label: "संस्कृति-धर्म",
    categories: [
      { slug: "dharm-adhyatm", label: "धर्म अध्यात्म" },
      { slug: "prerak-prasang", label: "प्रेरक प्रसंग" },
      { slug: "hindu-dharm", label: "हिंदू धर्म और जनजीवन" },
      { slug: "pooja-karmkand", label: "पूजा पाठ और कर्मकांड" },
      { slug: "bhartiya-sabhyata", label: "भारतीय सभ्यता और संस्कृति" },
      { slug: "pashchimi-sanskriti", label: "पश्चिमी संस्कृति" },
      { slug: "parv-tyohar", label: "पर्व त्यौहार" },
      { slug: "dharohar", label: "धरोहर" },
      { slug: "sanskritik-virasat", label: "सांस्कृतिक विरासत" },
      { slug: "puratatv-smarak", label: "पुरातत्व और स्मारक" },
      { slug: "tirthyatra", label: "तीर्थयात्रा" },
      { slug: "vivah-mandap", label: "विवाह मंडप" },
      { slug: "janmdin-samaroh", label: "जन्मदिन समारोह" },
      { slug: "varshganth", label: "वर्षगांठ" },
      { slug: "punya-smriti", label: "पुण्य स्मृति" },
    ],
  },
  {
    slug: "jeevanshaili",
    label: "जीवनशैली",
    categories: [
      { slug: "swasthya-charcha", label: "स्वास्थ्य चर्चा" },
      { slug: "bimari-mahamari", label: "बीमारियां और महामारी" },
      { slug: "yog-aasan", label: "योग और आसन" },
      { slug: "vyayam-kasrat", label: "व्यायाम और कसरत" },
      { slug: "khanpan-aahar", label: "खानपान और आहार" },
      { slug: "fashion", label: "फ़ैशन की दुनिया" },
      { slug: "paryatan-sair", label: "पर्यटन और सैर सपाटा" },
      { slug: "samudra-tat", label: "समुद्र तट" },
      { slug: "cinema-manoranjan", label: "सिनेमा और मनोरंजन" },
      { slug: "khel-khiladi", label: "खेल और खिलाड़ी" },
      { slug: "yuva-jagat", label: "युवा जगत" },
      { slug: "grih-samasya", label: "गृह समस्या" },
      { slug: "nagrik-uddayan", label: "नागरिक उड्डयन" },
      { slug: "bhartiya-rail", label: "भारतीय रेल" },
    ],
  },
  {
    slug: "arth-paryavaran",
    label: "अर्थ-पर्यावरण",
    categories: [
      { slug: "mudra-mandi", label: "मुद्रा और मंडी" },
      { slug: "vyapar-vanijya", label: "व्यापार वाणिज्य" },
      { slug: "corporate-jagat", label: "कार्पोरेट जगत" },
      { slug: "shram-jagat", label: "श्रम जगत" },
      { slug: "rojgar-samachar", label: "रोजगार समाचार" },
      { slug: "krishi-jagat", label: "कृषि जगत" },
      { slug: "bagwani", label: "बागवानी" },
      { slug: "pushpodyan", label: "पुष्पोद्यान" },
      { slug: "gramodyog-hastshilp", label: "ग्रामोद्योग और हस्तशिल्प" },
      { slug: "paryavaran-sanrakshan", label: "पर्यावरण संरक्षण" },
      { slug: "vanya-jeevan", label: "वन्य जीवन" },
      { slug: "vanaspati-jagat", label: "वनस्पति जगत" },
      { slug: "jeev-jantu", label: "जीव-जंतुओं की दुनिया" },
      { slug: "aapda-prabandhan", label: "आपदा प्रबंधन" },
    ],
  },
];